### ISSUE TITLE
Layout structure of modular compiler

### ISSUE THREAD

**Issue by teaguetomesh** [teaguetomesh/c2qa-modular-qc#10]
Discussed in person at Princeton.

The ModularCompiler should iterate through 5 different steps

1. Distribute (via SCOTCH)
2. Assign qubits (based on front layer of gates)
3. Global Communication (Skipped in the first iteration)
4. Construct Local Circuits (Greedy construction right now)
5. Local Compile (Qiskit transpilers)

**Comment by weiT1993** [comment]
Moved the discussion to #15
